export const IconTypes = {
  ICON: {
    // NAVS
    ARROW_BACK: "ICON_ARROW_BACK",
    BROWSE: "ICON_BROWSE",
    BROWSE_SEARCH: "ICON_BROWSE_SEARCH",
    CHEVRON_DOWN: "ICON_CHEVRON_DOWN",
    CHEVRON_LEFT: "ICON_CHEVRON_LEFT",
    CHEVRON_RIGHT: "ICON_CHEVRON_RIGHT",
    CHEVRON_UP: "ICON_CHEVRON_UP",
    EXPLORE: "ICON_EXPLORE",
    HOME_FILL: "ICON_HOME_FILL",
    HOME_OUTLINE: "ICON_HOME_OUTLINE",
    LIVE: "ICON_LIVE",
    PROFILE: "ICON_PROFILE",
    SEARCH: "ICON_SEARCH",
    SETTINGS: "ICON_SETTINGS",
    X_CLOSE: "ICON_X_CLOSE",
    // INDICATORS
    BOLT: "ICON_BOLT",
    CAMERA: "ICON_CAMERA",
    CLIP: "ICON_CLIP",
    EYE: "ICON_EYE",
    EYE_X: "ICON_EYE_X",
    FACTOIDS_FILL: "ICON_FACTOIDS_FILL",
    FACTOIDS_OUTLINE: "ICON_FACTOIDS_OUTLINE",
    LOCKED: "ICON_LOCKED",
    PHONE: "ICON_PHONE",
    PLAYLIST: "ICON_PLAYLIST",
    PODCAST: "ICON_PODCAST",
    YIELD: "ICON_YIELD",
    UHD_4K: "ICON_UHD_4K",
    LONG_PRESS: "ICON_LONG_PRESS",
    // ACTIONS
    ADD: "ICON_ADD",
    CHECKED: "ICON_CHECKED",
    CIRCLE: "ICON_CIRCLE",
    MORE_VERTICAL: "ICON_MORE_VERTICAL",
    MORE_HORIZONTAL: "ICON_MORE_HORIZONTAL",
    INFO: "ICON_INFO",

    SIZE: {
      XL: "XL",
      L: "L",
      M: "M",
      S: "S",
      XS: "XS"
    }
  }
};
