export const ImageTypes = {
  IMG: {
    // Tiles
    BASIC: "IMG_BASIC",
    DETAIL: "IMG_DETAIL",
    HERO: "IMG_HERO",
    HIGHLIGHT_MINI: "IMG_HIGHLIGHT_MINI",
    HIGHLIGHT_LARGE: "IMG_HIGHLIGHT_LARGE",
    POSTER: "IMG_POSTER",
    STANDARD_EPISODE: "IMG_STANDARD_EPISODE",
    STANDARD_CLIP: "IMG_STANDARD_CLIP",
    STANDARD_LIVE: "IMG_STANDARD_LIVE",

    // IMAGE FORMATS
    FORMAT: {
      JPEG: "jpeg",
      JPG: "jpg",
      PNG: "png"
    }
  }
};
