export const LogoTypes = {
  LOGO: {
    NETWORK_GLOBAL_HEADER: "LOGO_NETWORK_GLOBAL_HEADER",
    MVPD_GLOBAL_HEADER: "LOGO_MVPD_GLOBAL_HEADER",
    NETWORK_DEFAULT: "LOGO_NETWORK_DEFAULT",
    NETWORK_SUCCESS: "LOGO_NETWORK_SUCCESS",
    NETWORK_SHOWHERO: "LOGO_NETWORK_SHOWHERO",
    NETWORK_SELECTOR_CHANNEL_LOGO: "LOGO_NETWORK_SELECTOR_CHANNEL_LOGO"
  }
};
