export const ScreenTypes = {
  SCREEN: {
    HOME: "SCREEN_HOME",
    SHOW: "SCREEN_SHOW",
    PLAYLIST: "SCREEN_PLAYLIST",
    SEARCH: "SCREEN_SEARCH",
    LIVE: "SCREEN_LIVE",
    VIDEO: "SCREEN_VIDEO",
    BROWSE: "SCREEN_BROWSE",
    SETTINGS: "SCREEN_SETTINGS"
  }
};
