export const ToastTypes = {
  TOAST: {
    FAV_NOTIFICATION: "TOAST_FAV_NOTIFICATION",
    FAV_SHOW_ADDED: "TOAST_FAV_SHOW_ADDED",
    FAV_SHOW_REMOVED: "TOAST_FAV_SHOW_REMOVED",
    FAV_EPISODE_ADDED: "TOAST_FAV_EPISODE_ADDED",
    FAV_EPISODE_REMOVED: "TOAST_FAV_EPISODE_REMOVED",
    FAV_ANONYMOUS: "TOAST_FAV_ANONYMOUS"
  }
};
